### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by ghost** [micah686/VnManager#2]
Hello. 
Thanks for the new update. I've run into a few issues.

1. Can't login. Adding VN's manually works.
2. Categories tab should be resizable. A big title will take up majority of screen making VN Info tab unreadable The title could be text wrapped.
3. Cannot open Advanced column. I'm guessing this is some unimplemented feature?
4. Switching Visual Novels is rather slow.  When switching rapidly from one entry to another, I occasionally encountered it freezing on one specific entry. Behaviour could be returned to normal by navigating to character or other tab.

**Comment by micah686** [comment]
Could you upload the log files in Data/logs please?

**Comment by xd1986k** [comment]
I looked at the simple log file and it had the following "Could not connect to Vndb API over SSL"
When I browsed to api.vndb.org, it gave me the following error

> NET::ERR_CERT_COMMON_NAME_INVALID
Subject: blicky.net
Issuer: Let's Encrypt Authority X3
Expires on: Dec 28, 2017
Current date: Nov 11, 2017

Here are the log files.
[2017-11-10-Simple.log](https://github.com/micah686/Visual-Novel-Manager-v2/files/1463314/2017-11-10-Simple.log)
[2017-11-10-Detailed.log](https://github.com/micah686/Visual-Novel-Manager-v2/files/1463315/2017-11-10-Detailed.log)

**Comment by micah686** [comment]
1) I'm looking into the issue. Some of my older builds seem to be having the same issue(even though they weren't before). So it *might* be something with the SSL certificate with the API. I'm not sure at this point.
2) I'll look into that. I thought I had it automatically wrap, but I may have removed it when changing things at some point.
3) Yes, the advanced column was for features that have not been implemented yet. I'll hide it on the next release until I have something to put there.
4) Yes, I know it sometimes freezes, because the progress indicator sometimes doesn't want to show properly. The first time you click on a game, it downloads the images, so it will freeze for longer. After that, it should only freeze for a second or two as it retrieves data from the database.

**Comment by xd1986k** [comment]
Good luck.
I should also mention that the You've played and Last played data is in each others columns.

**Comment by edgar1016** [comment]
I'm having the same issue. project hasn't been updated in a while I see though odds of this getting fixed?

**Comment by micah686** [comment]
Visual studio has been giving me problems, as well as the last version of the API library I was using. When I upgrade my computer(which should be in about a month or so), I'll get back to working on it. There was a fix for the API implemented, so I'm not sure if that fixed the issue yet. 

Don't worry, I still plan on fixing this. I'm just on hiatus from the project for now. I'll definitely check on how I can fix the bug(since the bug was happening to me, even on a build that worked in the past.)

**Comment by edgar1016** [comment]
Awesome thanks for the reply, looking forward to future updates!

**Comment by Nikey646** [comment]
The login issue is most likely related to the fact for some reason using the API you must have all lowercase in your username. If you have capital letters in your username when submitting the login request, it'll fail saying unknown username and password.

I've asked for clarification on this issue in the [API thread](https://vndb.org/t3599.201) on vndb. If i'm correct, either the change will be simple to do, or no change will be required (Because Yorhel is awesome and does us a small favor server side ;D)

**Comment by edgar1016** [comment]
Logging in is still broken on my end crashes immediately, my username doesn't contain any uppercase letters.

**Comment by Nikey646** [comment]
Yup, but logging in works...lol, for me when trying to load the wishlist, [this code](https://github.com/micah686/Visual-Novel-Manager-v2/blob/master/VisualNovelManagerv2/ViewModel/VisualNovels/VnListViewModel/VnListViewModel.cs#L649) causes a crash because i have nothing on my wishlist

**Comment by micah686** [comment]
Closed due to updated version not (__*Intentionally*__) having support for logging into the API
