### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ShinRaikdou** [micah686/VnManager#3]
1) Some characters doesn't show info. "Anata o Otoko ni Shite Ageru!" for example, or "Girls Be Ambitious!".
2) Can't login to vndb(wrong password).
3) After I launched any vn, I can't open page with it, because it gives me "VisualNovelManagerv2 has stopped working". (I think an issue in timer?)

And few suggestions:
1) Sorting by name(VN and Categories).
2) Rename categories.
3) Add VNDB link to the description.
4) Edit path to game(.exe)
5) Is that possible to add path by Shortcut? Because some games have commands on .exe files, like forcing window mode or AGTH programm.

**Comment by micah686** [comment]
---Issues---
1)It seems to be an issue with the trait converter. I'll look into it.
2) I'm trying to find out what's going on with logging into vndb. There are multiple places the issue may be coming from, and not all of them from my end, so it's somewhat difficult to narrow down.
3)Could you give me a picture, gif, or explain it in more detail? Do you mean that switching to a page such as character, screenshots,... while a game is running causes a crash?

---Suggestions---
1)I might add, depending on how hard it is to implement.
2)I'll add this later, but it's going to wait until I fix some bugs that are causing crashes.
3)I'll add this later, again. Should be like a 5 minute fix.
4)I'll look into this later
5) I might add this later. I'm considering this as an advanced option, having you change an option to enable this, since I can't validate all possible commands.
This is an advanced feature that I probably won't add for a while, so the only option as of now(keep in mind, this method is untested), is to open the database in something like DB Browser for SQLite, find the ```VnUserData``` table, and modifying the values of ```ExePath``` with the arguments.

**Comment by ShinRaikdou** [comment]
> 3)Could you give me a picture, gif, or explain it in more detail? Do you mean that switching to a page such as character, screenshots,... while a game is running causes a crash?

Sure. Here - https://i.imgur.com/v1To3hT.gif

**Comment by micah686** [comment]
I _think_ that switching while a game is still loading is causing the crash.
Could you:
1) Do what you did before, but wait about 30 seconds between each click, and see if the issue still occurs(to see if it is a timing issue).
2) Copy/upload the logs(if any) from ```Data/logs```

**Comment by ShinRaikdou** [comment]
But I quit a game and reloaded VNM2. I mean every game that I launched becomes broken. I can wait 30 sec, 5 minutes - it is still the same, I can't even go to page with it and launch it again.

Here my logs.
https://drive.google.com/open?id=1fGvdQIIdO9BvWbN0F_eLY9j9jd1t6WRb

**Comment by Nikey646** [comment]
For your second issue, logging in...[refer to this](https://github.com/micah686/Visual-Novel-Manager-v2/issues/2#issuecomment-388553014)

**Comment by micah686** [comment]
Closed due to work on new version. Old version is no longer supported.
